name: RTx::EmailCompletion
version: 0.01
abstract: Add autocompletion on email address field
author: Nicolas Chuche <nchuche@barna.be>
license: mit
distribution_type: module
requires:
  RT: 0
no_index:
  directory:
    - html
    - inc
generated_by: handmade
